version: '3.2'

services:
  iris:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: irissec
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - ./shared:/shared

  httpd:
    build:
      dockerfile: Dockerfile
      context: httpd
    container_name: httpd
    ports:
    - "8080:80"
    - "443:443"
    volumes:
    - ./shared:/shared
